
name: Test Build

on: 
  push:
    branches: 'master'

jobs:
  check-and-publish:
    name: "Test job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout and Publish"
        uses: actions/checkout@v2
      - name: "Setup Node.js"
        uses: actions/setup@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: "Install dependencies"
        run: npm install
      - run: npm publish
