
name: Test Build

on:
  push:
    branches: 'master'

jobs:
  check-and-publish:
    name: "Test job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        
      - name: "Edit config"  
        run: git config --global user.email "boumrz@gmail.com" && git config --global user.name "boumrz"
      - name: "Version patch"
        run: npm version 0.1.${{GITHUB_RUN_ID}} 

      - name: "Install dependencies"
        run: npm install
      - name: "Npm publish"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: "telegram Notification"
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: New 0.1.${{GITHUB_RUN_ID}}  version publish 
